### ISSUE TITLE
build documentation missing 

### ISSUE THREAD

**Issue by MarcusWolschon** [Sardau/Sardauscan#1]
the readme.md does not cover what operating software and build environment is required nor how to configure the software for a specific laser line scanner (e.g.Fabscan Cube)

**Comment by Sardau** [comment]
Hello, the software does not work directly for a fabscan, it work out of the bow with his own firmware for the sardauscan hardware.

but a "IHardwareProxy" will surely be easy to implement (see https://github.com/Sardau/Sardauscan/tree/master/Sardauscan/FakeHardwarePlugins for sample plugins). I Didn't own a fabscan so i can't help you on that.

as soon as a IHardwareproxy plugin is available, nothing to do to configure the soft for a specific hardware.
