### ISSUE TITLE
Does it work with two lasers?

### ISSUE THREAD

**Issue by bond4u** [Sardau/Sardauscan#12]
I have two lasers.
Calibrate > Quick scan
Shows fours shapes:
1. Laser0 - red
2. Laser1 - green
3. light blue
4. purple

**Comment by bond4u** [comment]
https://goo.gl/photos/a8QyXE4NxfLhCrwK8

**Comment by Sardau** [comment]
hello,

your camera is not perfectly vertical.
your "tune" of the laser doesn't seems ok ( too many error)
i think you must redo your calivration : 1mm is a HUGE error in physical calibration and in build dimention.
