### ISSUE TITLE
value for x dimension

### ISSUE THREAD

**Issue by scvette** [Sardau/Sardauscan#16]

**Comment by scvette** [comment]
I have been using my scanner for a long while and cannot find how to measure the X axis value for the lasers. Y and Z values are well documented, What is the dimension of the X value? Is it from the tip of the camera to the tip of the laser? Is it automatically determined when an accurate angle value input? Please add x info to the nice new docs.
Thanks for a great scanner!

**Comment by Sardau** [comment]
All the measurment from the center of rotation of the table.

if you place yourself at the "camera" place, you are at X=0 .  X>0 is on your right.

BTW : I've introduce a angle that is editable in the config bacause it is easier to print a "protractor". place it on the center of rotation and read the angle.
