### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by percramer** [Sardau/Sardauscan#18]
Hi,

Just found your project. I was wondering how accurate it is? We own a David3d scanner (hp now), so i could do Some compare. But maybe there already is Some info on this?

**Comment by podarok** [comment]
@percramer it depends from the camera resolution you'll be using for scan
I'm not sure if the software support other cameras atm, but I belive it is not that hard to make it working for High-Resolution cameras

**Comment by Sardau** [comment]
it depend on your camera, your build size and the quality of your calibration.
