### ISSUE TITLE
Sardauscan.exe crashes on open in windows 10

### ISSUE THREAD

**Issue by 3axis** [Sardau/Sardauscan#21]
Hi,

I only have a linux machine so I am running windows 10 in virtual box but Sardauscan.exe crashes as soon as I open it. Any ideas.

Spent a while building this thing would be nice to use it.

**Comment by Sardau** [comment]
Hello.
It seem to be some problemin some ressource on some machine, but i can't find why (dont get the problem :/ )

All i can say is recompile the solution on your machine and the problem go away.
