### ISSUE TITLE
error upon opening sardauscan

### ISSUE THREAD

**Issue by jmartens2** [Sardau/Sardauscan#23]
everytime it tries to open sardauscan.exe windows says the program has stopped working and checks for a solution. im running win 7 32 bit os.

**Comment by jmartens2** [comment]
wow. you can hear a pin drop. hi, anybody able to help a friend????

**Comment by nfuhler** [comment]
v0.0.0.3 (https://github.com/Sardau/Sardauscan/releases/tag/0.0.0.3) at least opens for me, I haven't gotten around to actually test the scanning but maybe you can give it a shot
