### ISSUE TITLE
Allow user to choose from available cameras

### ISSUE THREAD

**Issue by frankvdh** [Sardau/Sardauscan#3]
Working on a laptop with integrated webcam, I can't tell Sardauscan to use the camera plugged into the USB socket.

**Comment by strawdog74** [comment]
It remembers the first selection you make, I had this problem too!

To start over, go into the main setting page (the cogs the on the top right of the window), and scroll down until you find the LAST USED section. Then erase the field ICamera_Proxy_HARDWARE_ID.

Close the program and restart and you should find the webcam is selectable.
