### ISSUE TITLE
Typo in TableCommand processing

### ISSUE THREAD

**Issue by neildarlow** [Sardau/Sardauscan#6]
In the TableCommand function (within FirmWare.ino) the last character test checks for 'C' or 's' which I believe came about as a cut and paste error.

This could have been avoided with a construct like:

switch( toupper(arg[0]) )
{
    case 'R': // T R
        ...
        break;

```
case 'A': // T A
    ...
    break;

case 'S': // T S
    ...
    break;

case 'C': // T C
    ...
    break;

default:
    Serial.print("Unknown Table command :");
    Serial.println(arg);
```

}

This would generate less code in that only a single uppercase check is performed per character and the compiler has good semantics for processing switch statements efficiently.

**Comment by Sardau** [comment]
corrected thank you
