### ISSUE TITLE
Wiring diagram mismatch with software

### ISSUE THREAD

**Issue by frankvdh** [Sardau/Sardauscan#7]
The wiring diagram doesn't match up with the software as far as the lasers go:

Correct software to match the wiring diagram is:
# define LASER_PIN_1 13 //yellow
# define LASER_PIN_2 A1 //orange
# define LASER_PIN_3 A2 //green
# define LASER_PIN_4 A3 //blue

**Comment by Sardau** [comment]
noted thank you
