### ISSUE TITLE
PS3 Eye Support

### ISSUE THREAD

**Issue by strawdog74** [Sardau/Sardauscan#8]
Hi there,

I am using a PS3_Eye Webcam with the CL-Eye-Driver-5.3.0.0341 driver, which is supposed to support DirectShow however the camera is not being displayed in the drop-down list.

Do you know of anyone who has managed to get Sardauscan working with a PS3_Eye webcam?

Thanks // SD

**Comment by Sardau** [comment]
I use the standart directshow routine to get the available camera (same as opencv). if you don't see it, it is probably not supported.
